In [22]:
import numpy as np
import pandas as pd
import scipy.stats

pd.options.mode.chained_assignment = None
from matplotlib import pyplot as plt, rcParams
# import cv2
import seaborn as sns

sns.set(style="white", context="paper")
from cycler import cycler
import os, sys
import glob
from datetime import datetime, timedelta
from itertools import combinations
import base64
from PIL import Image
from io import BytesIO as _BytesIO
import requests
import json
import pickle
from datetime import datetime
from IPython.display import display, Markdown, Latex
from matplotlib import dates
from sklearn.metrics import *
import collections
from copy import deepcopy
pd.options.display.max_columns = None
def printm(s): return display(Markdown(s))

In [23]:
stress_dict = pickle.load(open('stress_scores_may13.pb','rb'))
stress_dict.keys()

dict_keys(['groundtruth', 'predicted', 'activities'])

In [24]:
gt_stress = stress_dict['groundtruth']
gt_stress
# pd.DataFrame(gt_stress, orient='columns')

{'00EABED2-271D-49D8-B599-1D4A09240601': [('2015-41',
   (2.0,
    {'2015-10-07': 0.16666666666666666,
     '2015-10-08': 0.16666666666666666,
     '2015-10-12': 0.16666666666666666,
     '2015-10-09': 0.08333333333333333,
     '2015-10-06': 0.16666666666666666,
     '2015-10-05': 0.3333333333333333})),
  ('2015-42',
   (2.0,
    {'2015-10-07': 0.16666666666666666,
     '2015-10-08': 0.16666666666666666,
     '2015-10-12': 0.16666666666666666,
     '2015-10-09': 0.08333333333333333,
     '2015-10-06': 0.16666666666666666,
     '2015-10-05': 0.3333333333333333}))],
 '0A986513-7828-4D53-AA1F-E02D6DF9561B': [('2015-50',
   (1.0,
    {'2015-12-11': 0.125,
     '2015-12-10': 0.125,
     '2015-12-09': 0.25,
     '2015-12-08': 0.25}))],
 '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842': [('2015-36',
   (1.5, {'2015-08-31': 0.25, '2015-08-26': 0.75})),
  ('2015-35', (1.5, {'2015-08-31': 0.25, '2015-08-26': 0.75}))],
 '1155FF54-63D3-4AB2-9863-8385D0BD0A13': [('2016-22',
   (2.0,
    {'2016-05-31': 0.125,
     '2016-05-30': 0.1875,
     '2016-05-29': 0.125,
     '2016-05-28': 0.125,
     '2016-05-27': 0.125,
     '2016-05-26': 0.0625,
     '2016-05-25': 0.1875,
     '2016-05-24': 0.0})),
  ('2016-21',
   (2.0,
    {'2016-05-31': 0.125,
     '2016-05-30': 0.1875,
     '2016-05-29': 0.125,
     '2016-05-28': 0.125,
     '2016-05-27': 0.125,
     '2016-05-26': 0.0625,
     '2016-05-25': 0.1875,
     '2016-05-24': 0.0}))],
 '0E6184E1-90C0-48EE-B25A-F1ECB7B9714E': [('2015-50',
   (4.5,
    {'2015-12-07': 0.1875,
     '2015-12-06': 0.1875,
     '2015-12-05': 0.1875,
     '2015-12-04': 0.4375,
     '2015-12-03': 0.1875,
     '2015-12-02': 0.4375,
     '2015-12-01': 0.4375,
     '2015-11-30': 0.5625})),
  ('2015-49',
   (4.5,
    {'2015-12-07': 0.1875,
     '2015-12-06': 0.1875,
     '2015-12-05': 0.1875,
     '2015-12-04': 0.4375,
     '2015-12-03': 0.1875,
     '2015-12-02': 0.4375,
     '2015-12-01': 0.4375,
     '2015-11-30': 0.5625}))],
 '098A72A5-E3E5-4F54-A152-BBDA0DF7B694': [('2015-35',
   (1.0,
    {'2015-08-28': 0.2,
     '2015-08-07': 0.2,
     '2015-08-06': 0.2,
     '2015-08-05': 0.1,
     '2015-08-04': 0.1})),
  ('2015-32',
   (1.0,
    {'2015-08-28': 0.2,
     '2015-08-07': 0.2,
     '2015-08-06': 0.2,
     '2015-08-05': 0.1,
     '2015-08-04': 0.1}))],
 '0BFC35E2-4817-4865-BFA7-764742302A2D': [('2015-44',
   (0.0,
    {'2015-10-27': -0.0625,
     '2015-10-26': -0.0625,
     '2015-10-25': -0.125,
     '2015-10-24': -0.125,
     '2015-10-23': -0.0625,
     '2015-10-22': -0.125,
     '2015-10-21': -0.125,
     '2015-10-20': 0.0625})),
  ('2015-43',
   (0.0,
    {'2015-10-27': -0.0625,
     '2015-10-26': -0.0625,
     '2015-10-25': -0.125,
     '2015-10-24': -0.125,
     '2015-10-23': -0.0625,
     '2015-10-22': -0.125,
     '2015-10-21': -0.125,
     '2015-10-20': 0.0625}))]}

In [25]:
gt_stress['00EABED2-271D-49D8-B599-1D4A09240601'][0][1]

(2.0,
 {'2015-10-07': 0.16666666666666666,
  '2015-10-08': 0.16666666666666666,
  '2015-10-12': 0.16666666666666666,
  '2015-10-09': 0.08333333333333333,
  '2015-10-06': 0.16666666666666666,
  '2015-10-05': 0.3333333333333333})

In [26]:
stress_data = []
for user_id in stress_dict['groundtruth']:
    for week_stress_info in stress_dict['groundtruth'][user_id]:
        week, week_stress  = week_stress_info[0],week_stress_info[1]
        print(week_stress)
        for day in week_stress[1]:
            stress_data.append([user_id,day,week_stress[1][day],'gt'])

for user_id in stress_dict['predicted']:
    for week_stress_info in stress_dict['predicted'][user_id]:
        week, week_stress  = week_stress_info[0],week_stress_info[1]
        for day in week_stress[1]:
            stress_data.append([user_id,day,week_stress[1][day],'predicted'])
            
for user_id in stress_dict['activities']:
    for week_stress_info in stress_dict['activities'][user_id]:
        week, week_stress  = week_stress_info[0],week_stress_info[1]
        for day in week_stress[1]:
            stress_data.append([user_id,day,week_stress[1][day],'activities'])

df_stress = pd.DataFrame(stress_data, columns=['user_id','date','stress-score','type']).sort_values(by=['user_id','date'])
df_stress.info()
df_stress.head()

(2.0, {'2015-10-07': 0.16666666666666666, '2015-10-08': 0.16666666666666666, '2015-10-12': 0.16666666666666666, '2015-10-09': 0.08333333333333333, '2015-10-06': 0.16666666666666666, '2015-10-05': 0.3333333333333333})
(2.0, {'2015-10-07': 0.16666666666666666, '2015-10-08': 0.16666666666666666, '2015-10-12': 0.16666666666666666, '2015-10-09': 0.08333333333333333, '2015-10-06': 0.16666666666666666, '2015-10-05': 0.3333333333333333})
(1.0, {'2015-12-11': 0.125, '2015-12-10': 0.125, '2015-12-09': 0.25, '2015-12-08': 0.25})
(1.5, {'2015-08-31': 0.25, '2015-08-26': 0.75})
(1.5, {'2015-08-31': 0.25, '2015-08-26': 0.75})
(2.0, {'2016-05-31': 0.125, '2016-05-30': 0.1875, '2016-05-29': 0.125, '2016-05-28': 0.125, '2016-05-27': 0.125, '2016-05-26': 0.0625, '2016-05-25': 0.1875, '2016-05-24': 0.0})
(2.0, {'2016-05-31': 0.125, '2016-05-30': 0.1875, '2016-05-29': 0.125, '2016-05-28': 0.125, '2016-05-27': 0.125, '2016-05-26': 0.0625, '2016-05-25': 0.1875, '2016-05-24': 0.0})
(4.5, {'2015-12-07': 0.1875, '2015-12-06': 0.1875, '2015-12-05': 0.1875, '2015-12-04': 0.4375, '2015-12-03': 0.1875, '2015-12-02': 0.4375, '2015-12-01': 0.4375, '2015-11-30': 0.5625})
(4.5, {'2015-12-07': 0.1875, '2015-12-06': 0.1875, '2015-12-05': 0.1875, '2015-12-04': 0.4375, '2015-12-03': 0.1875, '2015-12-02': 0.4375, '2015-12-01': 0.4375, '2015-11-30': 0.5625})
(1.0, {'2015-08-28': 0.2, '2015-08-07': 0.2, '2015-08-06': 0.2, '2015-08-05': 0.1, '2015-08-04': 0.1})
(1.0, {'2015-08-28': 0.2, '2015-08-07': 0.2, '2015-08-06': 0.2, '2015-08-05': 0.1, '2015-08-04': 0.1})
(0.0, {'2015-10-27': -0.0625, '2015-10-26': -0.0625, '2015-10-25': -0.125, '2015-10-24': -0.125, '2015-10-23': -0.0625, '2015-10-22': -0.125, '2015-10-21': -0.125, '2015-10-20': 0.0625})
(0.0, {'2015-10-27': -0.0625, '2015-10-26': -0.0625, '2015-10-25': -0.125, '2015-10-24': -0.125, '2015-10-23': -0.0625, '2015-10-22': -0.125, '2015-10-21': -0.125, '2015-10-20': 0.0625})
<class 'pandas.core.frame.DataFrame'>
Int64Index: 234 entries, 5 to 174
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       234 non-null    object
 1   date          234 non-null    object
 2   stress-score  234 non-null    float64
 3   type          234 non-null    object
dtypes: float64(1), object(3)
memory usage: 9.1+ KB

,user_id,date,stress-score,type
5,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,0.333333,gt
11,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,0.333333,gt
83,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,0.514902,predicted
89,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,0.514902,predicted
161,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,0.333333,activities

In [27]:
df_stress_table = pd.pivot_table(df_stress, index=['user_id','date'], columns='type',values='stress-score',aggfunc='mean')

In [28]:
df_stress_table = df_stress_table.reset_index()
df_stress_table

type,user_id,date,activities,gt,predicted
0,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,0.333333,0.333333,0.514902
1,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-06,0.166667,0.166667,0.314902
2,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-07,0.166667,0.166667,0.333333
3,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-08,0.166667,0.166667,0.333333
4,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-09,0.166667,0.083333,0.253333
5,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-12,0.166667,0.166667,0.333529
6,098A72A5-E3E5-4F54-A152-BBDA0DF7B694,2015-08-04,0.400000,0.100000,0.000000
7,098A72A5-E3E5-4F54-A152-BBDA0DF7B694,2015-08-05,0.200000,0.100000,0.000000
8,098A72A5-E3E5-4F54-A152-BBDA0DF7B694,2015-08-06,0.200000,0.200000,0.200000
9,098A72A5-E3E5-4F54-A152-BBDA0DF7B694,2015-08-07,0.200000,0.200000,0.200000
10,098A72A5-E3E5-4F54-A152-BBDA0DF7B694,2015-08-28,0.200000,0.200000,0.200000
11,0A986513-7828-4D53-AA1F-E02D6DF9561B,2015-12-08,0.500000,0.250000,0.000000
12,0A986513-7828-4D53-AA1F-E02D6DF9561B,2015-12-09,0.250000,0.250000,0.000000
13,0A986513-7828-4D53-AA1F-E02D6DF9561B,2015-12-10,0.250000,0.125000,0.000000
14,0A986513-7828-4D53-AA1F-E02D6DF9561B,2015-12-11,0.250000,0.125000,0.125000
15,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-20,0.187500,0.062500,0.066400
16,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-21,0.062500,-0.125000,-0.099554
17,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-22,0.062500,-0.125000,-0.120728
18,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-23,0.062500,-0.062500,-0.054792
19,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-24,0.062500,-0.125000,-0.124443
20,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-25,0.062500,-0.125000,-0.124629
21,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-26,0.062500,-0.062500,-0.110420
22,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-27,0.062500,-0.062500,-0.056835
23,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-11-30,0.250000,0.562500,0.500000
24,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-01,0.125000,0.437500,0.375000
25,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-02,0.125000,0.437500,0.375000
26,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-03,0.125000,0.187500,0.375000
27,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-04,0.125000,0.437500,0.375000
28,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-05,0.125000,0.187500,0.125000
29,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-06,0.125000,0.187500,0.125000
30,0E6184E1-90C0-48EE-B25A-F1ECB7B9714E,2015-12-07,0.125000,0.187500,0.187500
31,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-24,0.250000,0.000000,0.312500
32,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-25,0.125000,0.187500,0.250000
33,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-26,0.125000,0.062500,0.125000
34,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-27,0.125000,0.125000,0.187500
35,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-28,0.125000,0.125000,0.187500
36,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-29,0.125000,0.125000,0.187500
37,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-30,0.125000,0.187500,0.250000
38,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-31,0.125000,0.125000,0.187500
39,1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842,2015-08-26,1.000000,0.750000,1.500000
40,1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842,2015-08-31,0.500000,0.250000,0.500000

In [29]:
df_stress_table.to_csv("stress_score_final_may13.csv",index=False)

In [30]:
selected_users = ['7D9BB102-A612-4E2A-8E22-3159752F55D8',
 '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842',
 '1538C99F-BA1E-4EFB-A949-6C7C47701B20',
'7CE37510-56D0-4120-A1CF-0E23351428D2',
'1155FF54-63D3-4AB2-9863-8385D0BD0A13',
'0BFC35E2-4817-4865-BFA7-764742302A2D']
df_stress_table_selected_users = df_stress_table[df_stress_table.user_id.isin(selected_users)].sort_values(by=['user_id','date'])

In [31]:
df_stress_table_selected_users

type,user_id,date,activities,gt,predicted
15,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-20,0.1875,0.0625,0.066400
16,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-21,0.0625,-0.1250,-0.099554
17,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-22,0.0625,-0.1250,-0.120728
18,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-23,0.0625,-0.0625,-0.054792
19,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-24,0.0625,-0.1250,-0.124443
20,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-25,0.0625,-0.1250,-0.124629
21,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-26,0.0625,-0.0625,-0.110420
22,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-27,0.0625,-0.0625,-0.056835
31,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-24,0.2500,0.0000,0.312500
32,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-25,0.1250,0.1875,0.250000
33,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-26,0.1250,0.0625,0.125000
34,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-27,0.1250,0.1250,0.187500
35,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-28,0.1250,0.1250,0.187500
36,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-29,0.1250,0.1250,0.187500
37,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-30,0.1250,0.1875,0.250000
38,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-31,0.1250,0.1250,0.187500
39,1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842,2015-08-26,1.0000,0.7500,1.500000
40,1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842,2015-08-31,0.5000,0.2500,0.500000

In [34]:
df_stress_table_selected_users

type,user_id,date,activities,gt,predicted
15,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-20,0.1875,0.0625,0.065911
16,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-21,0.0625,-0.1250,-0.103314
17,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-22,0.0625,-0.1250,-0.122198
18,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-23,0.0625,-0.0625,-0.046499
19,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-24,0.0625,-0.1250,-0.122117
20,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-25,0.0625,-0.1250,-0.124594
21,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-26,0.0625,-0.0625,-0.112370
22,0BFC35E2-4817-4865-BFA7-764742302A2D,2015-10-27,0.0625,-0.0625,-0.059820
31,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-24,0.2500,0.0000,0.188770
32,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-25,0.1250,0.1875,0.251778
33,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-26,0.0625,0.0625,0.137576
34,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-27,0.1250,0.1250,0.193598
35,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-28,0.1250,0.1250,0.212398
36,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-29,0.1250,0.1250,0.190168
37,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-30,0.1250,0.1875,0.256606
38,1155FF54-63D3-4AB2-9863-8385D0BD0A13,2016-05-31,0.1250,0.1250,0.194106
39,1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842,2015-08-26,1.0000,0.7500,1.500000
40,1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842,2015-08-31,0.2500,0.2500,0.500000