In [1]:
import numpy as np
import pandas as pd
import scipy.stats

pd.options.mode.chained_assignment = None
from matplotlib import pyplot as plt, rcParams
# import cv2
import seaborn as sns

sns.set(style="white", context="paper")
from cycler import cycler
import os, sys
import glob
from datetime import datetime, timedelta
from itertools import combinations
import base64
from PIL import Image
from io import BytesIO as _BytesIO
import requests
import json
import pickle
from datetime import datetime
from IPython.display import display, Markdown, Latex
from sklearn.metrics import *
import collections
from copy import deepcopy
pd.options.display.max_columns = None
def printm(s): return display(Markdown(s))

In [2]:
def get_weekly_stress_score(week_context_attributes):
    """
    Return stress score for the week
    :param week_context_attributes: How days context looks like
    :return: weekly stress score based on FSM
    """
    stress_score = 0.
    total_days_data_in_week = len(week_context_attributes.keys())

    # Condition 1: Context of exercising and housework existing in 57% of week: -1 stress score
    c1_exercise_count, c1_housework_count = 0.,0.
    for day in week_context_attributes.keys():
        if 'Exercising' in week_context_attributes[day].context.values:
            c1_exercise_count +=1
        if 'HouseWork' in week_context_attributes[day].context.values:
            c1_housework_count+=1

    if ((c1_exercise_count/total_days_data_in_week) >= 0.57) and ((c1_housework_count/total_days_data_in_week) >= 0.57):
        stress_score -= 1

    # Condition 2a: No context of exercising for more than 57% week(4 days if full week available): +0.5 stress score
    # Condition 2b: No context of housework  for more than 4 days(57% week): +0.5 stress score
    c2a_exercise_count = c1_exercise_count
    c2b_housework_count = c1_housework_count

    if (c2a_exercise_count/total_days_data_in_week) < 0.57:
        stress_score += 0.5
    if (c2b_housework_count/total_days_data_in_week) < 0.57:
        stress_score += 0.5

    # Condition 3: context of commute for more than an hour(on average) in a day everyday: +0.5 stress score
    c3_commute_hours = []
    for day in week_context_attributes:
        if 'Commuting' not in week_context_attributes[day].context.values:
            c3_commute_hours.append(0.)
        else:
            day_commute_values = week_context_attributes[day][week_context_attributes[day].context=='Commuting']
            day_commute_values['period'] = day_commute_values['end'] - day_commute_values['start']
            c3_commute_hours.append(day_commute_values['period'].sum())

    if np.mean(c3_commute_hours) > (60*60): # more than 1 hours of average commute
        stress_score +=0.5


    # condition 4a: context of sleep for less than 6 hours on more than 3 days(42% week): +1 stress score
    # condition 4b: context of sleep for less more than 8 hours on an average: -0.5 stress score
    c4_sleep_hours = []
    for day in week_context_attributes:
        if 'Sleeping' not in week_context_attributes[day].context.values:
            c4_sleep_hours.append(0.)
        else:
            day_sleep_values = week_context_attributes[day][week_context_attributes[day].context == 'Sleeping']
            day_sleep_values['period'] = day_sleep_values['end'] - day_sleep_values['start']
            c4_sleep_hours.append(day_sleep_values['period'].sum())

    if np.max(sorted(c4_sleep_hours)[:3]) < (6 * 60 * 60):  # 4a.less than 6 hours of sleep for 3 days
        stress_score += 1

    if np.mean(c4_sleep_hours) > (8 * 60 * 60):  # 4b. more than 8 hours of sleep
        stress_score -= 0.5

    # condition 5: (More than 4 days(57%) of Exercising context for more than half an hour) &
    # (Different working hours (>40% difference) across days): +0.5 stress score
    c5_exercising_count = c1_exercise_count
    c5_exercising_hours = []
    for day in week_context_attributes:
        if 'Exercising' in week_context_attributes[day].context.values:
            day_exercise_values = week_context_attributes[day][week_context_attributes[day].context == 'Exercising']
            day_exercise_values['period'] = day_exercise_values['end'] - day_exercise_values['start']
            c5_exercising_hours.append(day_exercise_values['period'].sum())
    c5_exercise_cond = False
    if ((c5_exercising_count/total_days_data_in_week) >= 0.57) and (np.min(c5_exercising_hours) > (0.5*60*60)):
        c5_exercise_cond = True

    c5_working_periods = {}
    for day in week_context_attributes:
        if 'OfficeWork' in week_context_attributes[day].context.values:
            day_work_values = week_context_attributes[day][week_context_attributes[day].context == 'OfficeWork']
            day_work_values['start_hour'] = pd.to_datetime(day_work_values['start'],unit='s').dt.hour
            day_work_values['end_hour'] = pd.to_datetime(day_work_values['end'], unit='s').dt.hour
            c5_working_periods[day] = np.zeros(24)
            for idx, row in day_work_values.iterrows():
                c5_working_periods[day][row['start_hour']:row['end_hour']+1] = 1

    c5_hour_differences= [0.]
    for dayA in c5_working_periods.keys():
        for dayB in c5_working_periods.keys():
            if not (dayA==dayB):
                working_hoursA = c5_working_periods[dayA]
                working_hoursB = c5_working_periods[dayB]
                diff_hours = np.sum(working_hoursA!=working_hoursB)
                same_hours = np.sum(np.logical_and(working_hoursA==working_hoursB,working_hoursA))
                if same_hours > 0.:
                    c5_hour_differences.append(diff_hours / same_hours)
                else:
                    c5_hour_differences.append(0.)

    c5_working_cond = False
    if np.max(c5_hour_differences) > 0.4:
        c5_working_cond = True

    if (c5_working_cond) & (c5_exercise_cond):
        stress_score +=0.5

    # condition 6: (No context of exercising) & (Different working hours across days): +1 stress score
    c6_exercise_count=  c1_exercise_count
    c6_working_hour_diff = c5_hour_differences
    if (c6_exercise_count==0.) & (np.mean(c5_hour_differences) > 0.4):
        stress_score += 1

    # condition 7: (More than 4 days of Exercising context for more than half an hour) &
    # (No Different working hours (>40% difference)  across days): -1 stress score
    c7_exercise_cond = c5_exercise_cond
    c7_hour_differences = c5_hour_differences

    if (c7_exercise_cond) & (np.max(c7_hour_differences) < 0.4):
        stress_score -= 1.

    # condition 8: (More than 10 hrs of works in any day) OR (50+ hours per week): +1 stress score
    c8_work_hours = []
    for day in week_context_attributes:
        if 'OfficeWork' in week_context_attributes[day].context.values:
            day_work_values = week_context_attributes[day][week_context_attributes[day].context == 'OfficeWork']
            day_work_values['period'] = day_work_values['end'] - day_work_values['start']
            c8_work_hours.append(day_work_values['period'].sum())
        else:
            c8_work_hours.append(0.)

    if (np.max(c8_work_hours) > (10 * 60 * 60)) or (np.sum(c8_work_hours) > (50 * 60 * 60)):
        stress_score += 1

    # condition 9a: (More than 40% shift in working hours in max gap): +1 stress score
    # condition 9b: (More than 40% shift in working hours in 2 or more consecutive days): +1 stress score
    # Not modeling due to over complexity

    # condition 10a: More than 15 mins exercising every day: -0.5 stress score
    # condition 10b: More than 1 hour housework every day: -0.5 stress score
    c10a_exercising_hours = []
    for day in week_context_attributes:
        if 'Exercising' in week_context_attributes[day].context.values:
            day_exercise_values = week_context_attributes[day][week_context_attributes[day].context == 'Exercising']
            day_exercise_values['period'] = day_exercise_values['end'] - day_exercise_values['start']
            c10a_exercising_hours.append(day_exercise_values['period'].sum())
        else:
            c10a_exercising_hours.append(0.)

    c10b_housework_hours = []
    for day in week_context_attributes:
        if 'HouseWork' not in week_context_attributes[day].context.values:
            c10b_housework_hours.append(0.)
        else:
            day_housework = week_context_attributes[day][week_context_attributes[day].context == 'HouseWork']
            day_housework['period'] = day_housework['end'] - day_housework['start']
            c10b_housework_hours.append(day_housework['period'].sum())

    if np.min(c10a_exercising_hours) > 15 * 60:
        stress_score -=0.5

    if np.min(c10b_housework_hours) > 60 * 60:
        stress_score -= 0.5



    # condition 11a: Continuous 30 mins exercise, five times a week: -1 stress score
    # condition 11b: 15 mins exercise twice, five times a week: -1 stress score
    # condition 11c: 10 mins exercise thrice, five times a week: -1 stress score

    c11_day_cond = []
    for day in week_context_attributes.keys():
        if 'Exercising' not in week_context_attributes[day].context.values:
            c11_day_cond.append(False)
        else:
            day_exercise_values = week_context_attributes[day][week_context_attributes[day].context == 'OfficeWork']
            day_exercise_values['period'] = day_exercise_values['end'] - day_exercise_values['start']
            day_num_exercises = day_exercise_values.shape[0]
            day_min_continuous_exercise = day_exercise_values['period'].min()
            if (day_num_exercises >=1) and (day_min_continuous_exercise > 30*60):
                c11_day_cond.append(True)
            elif (day_num_exercises >=2) and (day_min_continuous_exercise > 15*60):
                c11_day_cond.append(True)
            elif (day_num_exercises >=3) and (day_min_continuous_exercise > 10*60):
                c11_day_cond.append(True)
            else:
                c11_day_cond.append(False)

    if (np.sum(c11_day_cond)/len(c11_day_cond)) > 0.7: # 5+ days in a week
        stress_score -= 1

    # condition 12: Working hours more than 8 for more than 5 days: +1 stress score
    c12_work_hours = c8_work_hours

    if np.percentile(c12_work_hours,0.7) > (8 * 60 * 60):
        stress_score += 1

    # condition 13a: Inactivity/Amusement for more than 2 hours everyday: -0.5 stress score
    # condition 13b: Inactivity/Amusement/Housework for more than 5 hours atleast two days: -0.5 stress score
    c13a_inactivity_amusement_hours = []
    for day in week_context_attributes:
        day_13a_hours = week_context_attributes[day][week_context_attributes[day].context.isin(['Inactivity','Amusement'])]
        if day_13a_hours.shape[0] > 0.:
            c13a_inactivity_amusement_hours.append((day_13a_hours['end'] - day_13a_hours['start']).sum())
        else:
            c13a_inactivity_amusement_hours.append(0.)

    c13b_inactivity_amusement_housework_hours = []
    for day in week_context_attributes:
        day_13b_hours = week_context_attributes[day][week_context_attributes[day].context.isin(['Inactivity','Amusement','HouseWork'])]
        if day_13b_hours.shape[0] > 0.:
            c13b_inactivity_amusement_housework_hours.append((day_13b_hours['end'] - day_13b_hours['start']).sum())
        else:
            c13b_inactivity_amusement_housework_hours.append(0.)

    if np.min(c13a_inactivity_amusement_hours) > (2 * 60 * 60):
        stress_score -= 0.5
    if np.percentile(c13b_inactivity_amusement_housework_hours, 30) > (5 * 60 * 60):
        stress_score -= 0.5

    # condition 14a: Working hours between 12am and 8am for any day: +1 stress score
    # condition 14b: Working hours between 12am and 8am for more than 4 days: +1 stress score

    c14_working_periods = c5_working_periods
    c14_night_work = []
    for day in c14_working_periods.keys():
        if np.sum(c14_working_periods[day][:8]) > 1:
            c14_night_work.append(True)
        else:
            c14_night_work.append(False)

    if np.sum(c14_night_work) >=1:
        stress_score +=1
    if np.sum(c14_night_work) >=4:
        stress_score += 1

    return stress_score

In [3]:
df_onto_casas = pd.read_csv("../../cache/trace_results/extrasensory_onto_trace.csv")
df_onto_casas['tao_prediction'] = df_onto_casas['tao_prediction'].apply(lambda x: x.split(";") if not (str(x)=='nan') else ['Unknown'])
df_onto_casas.head()

,timestamp,activities,id,tao_prediction
0,1444079161,"Sitting,In a meeting,With co-workers",00EABED2-271D-49D8-B599-1D4A09240601,[Unknown]
1,1444079221,"Sitting,In a meeting,With co-workers",00EABED2-271D-49D8-B599-1D4A09240601,[Unknown]
2,1444079281,"Sitting,In a meeting,With co-workers",00EABED2-271D-49D8-B599-1D4A09240601,[Unknown]
3,1444079341,"Sitting,In a meeting,With co-workers",00EABED2-271D-49D8-B599-1D4A09240601,[Unknown]
4,1444079431,"Sitting,In a meeting,With co-workers",00EABED2-271D-49D8-B599-1D4A09240601,[Unknown]

In [4]:
ts_dict = pickle.load(open("../../cache/trace_results/ts_results_extra.pb","rb"))
ts_results, cluster_labels = ts_dict['ts_results'], ts_dict['clusters']

In [30]:
list(ts_results.keys())

['00EABED2-271D-49D8-B599-1D4A09240601',
 '098A72A5-E3E5-4F54-A152-BBDA0DF7B694',
 '0A986513-7828-4D53-AA1F-E02D6DF9561B',
 '0BFC35E2-4817-4865-BFA7-764742302A2D',
 '0E6184E1-90C0-48EE-B25A-F1ECB7B9714E',
 '1155FF54-63D3-4AB2-9863-8385D0BD0A13',
 '11B5EC4D-4133-4289-B475-4E737182A406',
 '136562B6-95B2-483D-88DC-065F28409FD2',
 '1538C99F-BA1E-4EFB-A949-6C7C47701B20',
 '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842',
 '24E40C4C-A349-4F9F-93AB-01D00FB994AF',
 '27E04243-B138-4F40-A164-F40B60165CF3',
 '2C32C23E-E30C-498A-8DD2-0EFB9150A02E',
 '33A85C34-CFE4-4732-9E73-0A7AC861B27A',
 '3600D531-0C55-44A7-AE95-A7A38519464E',
 '40E170A7-607B-4578-AF04-F021C3B0384A',
 '481F4DD2-7689-43B9-A2AA-C8772227162B',
 '4E98F91F-4654-42EF-B908-A3389443F2E7',
 '4FC32141-E888-4BFF-8804-12559A491D8C',
 '5119D0F8-FCA8-4184-A4EB-19421A40DE0D',
 '5152A2DF-FAF3-4BA8-9CA9-E66B32671A53',
 '59818CD2-24D7-4D32-B133-24C2FE3801E5',
 '59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2',
 '5EF64122-B513-46AE-BCF1-E62AAC285D2C',
 '61359772-D8D8-480D-B623-7C636EAD0C81',
 '61976C24-1C50-4355-9C49-AAE44A7D09F6',
 '665514DE-49DC-421F-8DCB-145D0B2609AD',
 '74B86067-5D4B-43CF-82CF-341B76BEA0F4',
 '78A91A4E-4A51-4065-BDA7-94755F0BB3BB',
 '797D145F-3858-4A7F-A7C2-A4EB721E133C',
 '7CE37510-56D0-4120-A1CF-0E23351428D2',
 '7D9BB102-A612-4E2A-8E22-3159752F55D8',
 '8023FE1A-D3B0-4E2C-A57A-9321B7FC755F',
 '806289BC-AD52-4CC1-806C-0CDB14D65EB6',
 '81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0',
 '83CF687B-7CEC-434B-9FE8-00C3D5799BE6',
 '86A4F379-B305-473D-9D83-FC7D800180EF',
 '96A358A0-FFF2-4239-B93E-C7425B901B47',
 '9759096F-1119-4E19-A0AD-6F16989C7E1C',
 '99B204C0-DD5C-4BB7-83E8-A37281B8D769',
 '9DC38D04-E82E-4F29-AB52-B476535226F2',
 'A5A30F76-581E-4757-97A2-957553A2C6AA',
 'A5CDF89D-02A2-4EC1-89F8-F534FDABDD96',
 'A7599A50-24AE-46A6-8EA6-2576F1011D81',
 'A76A5AF5-5A93-4CF2-A16E-62353BB70E8A',
 'B09E373F-8A54-44C8-895B-0039390B859F',
 'B7F9D634-263E-4A97-87F9-6FFB4DDCB36C',
 'B9724848-C7E2-45F4-9B3F-A1F38D864495',
 'BE3CA5A6-A561-4BBD-B7C9-5DF6805400FC',
 'BEF6C611-50DA-4971-A040-87FB979F3FC1',
 'C48CE857-A0DD-4DDB-BEA5-3A25449B2153',
 'CA820D43-E5E2-42EF-9798-BE56F776370B',
 'CCAF77F0-FABB-4F2F-9E24-D56AD0C5A82F',
 'CDA3BBF7-6631-45E8-85BA-EEB416B32A3C',
 'CF722AA9-2533-4E51-9FEB-9EAC84EE9AAC',
 'D7D20E2E-FC78-405D-B346-DBD3FD8FC92B',
 'E65577C1-8D5D-4F70-AF23-B3ADB9D3DBA3',
 'ECECC2AB-D32F-4F90-B74C-E12A1C69BBE2',
 'F50235E0-DD67-4F2A-B00B-1F31ADA998B9',
 'FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF']

In [79]:
wellness_user_inputs = {}

In [7]:

id = '00EABED2-271D-49D8-B599-1D4A09240601'

In [80]:
for id in ts_results.keys():
    print(f"Start id {id}")
    df_ts_input =ts_results[id]
    df_ts_input.info()
    pred_min_ts, pred_max_ts = df_ts_input.start_timestamp.min(), df_ts_input.end_timestamp.max()
    df_pred_ts = pd.DataFrame(np.arange(pred_min_ts, pred_max_ts + 1), columns=['timestamp'])
    df_pred_ts['pred_context'] = None
    df_pred_ts = df_pred_ts.set_index('timestamp')
    for row_idx, row in df_ts_input.iterrows():
        df_pred_ts.loc[row['start_timestamp']:row['end_timestamp'], 'pred_context'] = df_pred_ts.loc[
                                                                                      row['start_timestamp']:
                                                                                      row['end_timestamp'],
                                                                                      'pred_context'].apply(
            lambda x: (x + cluster_labels[int(row['cluster_id'])]) if (x is not None) else cluster_labels[
                int(row['cluster_id'])])
    df_pred_ts = df_pred_ts.reset_index().rename(columns={'pred_context':'context'})
    df_pred_ts = df_pred_ts[~df_pred_ts.context.isnull()]
    df_pred_ts.head()
    df_onto_ts = df_onto_casas[df_onto_casas.id==id][['timestamp','tao_prediction']].rename(columns={'tao_prediction':'context'})
    df_onto_ts = df_onto_ts[~df_onto_ts.context.isnull()]
    df_onto_ts.head()
    df_combined_ts = pd.merge(df_onto_ts, df_pred_ts, on=['timestamp'], suffixes=('_onto','_tp'))
    df_combined_ts.head()
    df_combined_ts['context'] = df_combined_ts.apply(lambda row: ",".join(row['context_tp']+row['context_onto']),axis=1)
    df_combined_ts = df_combined_ts[['timestamp','context']]
    all_contexts = ['Exercising','HouseWork','Commuting','Sleeping','OfficeWork', 'Relaxing','Amusement','HavingMeal','UsingBathroom']
    for context in all_contexts:
        df_combined_ts[context] = df_combined_ts['context'].apply(lambda x: context in x)
    df_combined_ts = df_combined_ts.drop('context',axis=1)
    df_combined_ts = pd.melt(df_combined_ts, id_vars='timestamp',var_name='context',value_name='isPresent')
    df_combined_ts = df_combined_ts[df_combined_ts.isPresent==True][['timestamp','context']]
    wellness_user_inputs[id] =df_combined_ts
    print(f"Done id {id}")

Start id 00EABED2-271D-49D8-B599-1D4A09240601
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2081 entries, 0 to 2080
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       2081 non-null   float64
 1   next_start_timestamp  2081 non-null   float64
 2   end_timestamp         2081 non-null   float64
 3   cluster_id            2081 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 65.2 KB
Done id 00EABED2-271D-49D8-B599-1D4A09240601
Start id 098A72A5-E3E5-4F54-A152-BBDA0DF7B694
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5423 entries, 0 to 5422
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5423 non-null   float64
 1   next_start_timestamp  5423 non-null   float64
 2   end_timestamp         5423 non-null   float64
 3   cluster_id            5423 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 169.6 KB
Done id 098A72A5-E3E5-4F54-A152-BBDA0DF7B694
Start id 0A986513-7828-4D53-AA1F-E02D6DF9561B
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3865 entries, 0 to 3864
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       3865 non-null   float64
 1   next_start_timestamp  3865 non-null   float64
 2   end_timestamp         3865 non-null   float64
 3   cluster_id            3865 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 120.9 KB
Done id 0A986513-7828-4D53-AA1F-E02D6DF9561B
Start id 0BFC35E2-4817-4865-BFA7-764742302A2D
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1915 entries, 0 to 1914
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       1915 non-null   float64
 1   next_start_timestamp  1915 non-null   float64
 2   end_timestamp         1915 non-null   float64
 3   cluster_id            1915 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 60.0 KB
Done id 0BFC35E2-4817-4865-BFA7-764742302A2D
Start id 0E6184E1-90C0-48EE-B25A-F1ECB7B9714E
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6764 entries, 0 to 6763
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6764 non-null   float64
 1   next_start_timestamp  6764 non-null   float64
 2   end_timestamp         6764 non-null   float64
 3   cluster_id            6764 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 211.5 KB
Done id 0E6184E1-90C0-48EE-B25A-F1ECB7B9714E
Start id 1155FF54-63D3-4AB2-9863-8385D0BD0A13
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2396 entries, 0 to 2395
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       2396 non-null   float64
 1   next_start_timestamp  2396 non-null   float64
 2   end_timestamp         2396 non-null   float64
 3   cluster_id            2396 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 75.0 KB
Done id 1155FF54-63D3-4AB2-9863-8385D0BD0A13
Start id 11B5EC4D-4133-4289-B475-4E737182A406
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5346 entries, 0 to 5345
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5346 non-null   float64
 1   next_start_timestamp  5346 non-null   float64
 2   end_timestamp         5346 non-null   float64
 3   cluster_id            5346 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 167.2 KB
Done id 11B5EC4D-4133-4289-B475-4E737182A406
Start id 136562B6-95B2-483D-88DC-065F28409FD2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5905 entries, 0 to 5904
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5905 non-null   float64
 1   next_start_timestamp  5905 non-null   float64
 2   end_timestamp         5905 non-null   float64
 3   cluster_id            5905 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 184.7 KB
Done id 136562B6-95B2-483D-88DC-065F28409FD2
Start id 1538C99F-BA1E-4EFB-A949-6C7C47701B20
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6356 entries, 0 to 6355
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6356 non-null   float64
 1   next_start_timestamp  6356 non-null   float64
 2   end_timestamp         6356 non-null   float64
 3   cluster_id            6356 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 198.8 KB
Done id 1538C99F-BA1E-4EFB-A949-6C7C47701B20
Start id 1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6508 entries, 0 to 6507
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6508 non-null   float64
 1   next_start_timestamp  6508 non-null   float64
 2   end_timestamp         6508 non-null   float64
 3   cluster_id            6508 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 203.5 KB
Done id 1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842
Start id 24E40C4C-A349-4F9F-93AB-01D00FB994AF
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3156 entries, 0 to 3155
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       3156 non-null   float64
 1   next_start_timestamp  3156 non-null   float64
 2   end_timestamp         3156 non-null   float64
 3   cluster_id            3156 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 98.8 KB
Done id 24E40C4C-A349-4F9F-93AB-01D00FB994AF
Start id 27E04243-B138-4F40-A164-F40B60165CF3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2541 entries, 0 to 2540
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       2541 non-null   float64
 1   next_start_timestamp  2541 non-null   float64
 2   end_timestamp         2541 non-null   float64
 3   cluster_id            2541 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 79.5 KB
Done id 27E04243-B138-4F40-A164-F40B60165CF3
Start id 2C32C23E-E30C-498A-8DD2-0EFB9150A02E
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6545 entries, 0 to 6544
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6545 non-null   float64
 1   next_start_timestamp  6545 non-null   float64
 2   end_timestamp         6545 non-null   float64
 3   cluster_id            6545 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 204.7 KB
Done id 2C32C23E-E30C-498A-8DD2-0EFB9150A02E
Start id 33A85C34-CFE4-4732-9E73-0A7AC861B27A
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4611 entries, 0 to 4610
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       4611 non-null   float64
 1   next_start_timestamp  4611 non-null   float64
 2   end_timestamp         4611 non-null   float64
 3   cluster_id            4611 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 144.2 KB
Done id 33A85C34-CFE4-4732-9E73-0A7AC861B27A
Start id 3600D531-0C55-44A7-AE95-A7A38519464E
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3701 entries, 0 to 3700
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       3701 non-null   float64
 1   next_start_timestamp  3701 non-null   float64
 2   end_timestamp         3701 non-null   float64
 3   cluster_id            3701 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 115.8 KB
Done id 3600D531-0C55-44A7-AE95-A7A38519464E
Start id 40E170A7-607B-4578-AF04-F021C3B0384A
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5976 entries, 0 to 5975
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5976 non-null   float64
 1   next_start_timestamp  5976 non-null   float64
 2   end_timestamp         5976 non-null   float64
 3   cluster_id            5976 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 186.9 KB
Done id 40E170A7-607B-4578-AF04-F021C3B0384A
Start id 481F4DD2-7689-43B9-A2AA-C8772227162B
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5550 entries, 0 to 5549
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5550 non-null   float64
 1   next_start_timestamp  5550 non-null   float64
 2   end_timestamp         5550 non-null   float64
 3   cluster_id            5550 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 173.6 KB
Done id 481F4DD2-7689-43B9-A2AA-C8772227162B
Start id 4E98F91F-4654-42EF-B908-A3389443F2E7
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2431 entries, 0 to 2430
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       2431 non-null   float64
 1   next_start_timestamp  2431 non-null   float64
 2   end_timestamp         2431 non-null   float64
 3   cluster_id            2431 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 76.1 KB
Done id 4E98F91F-4654-42EF-B908-A3389443F2E7
Start id 4FC32141-E888-4BFF-8804-12559A491D8C
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4536 entries, 0 to 4535
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       4536 non-null   float64
 1   next_start_timestamp  4536 non-null   float64
 2   end_timestamp         4536 non-null   float64
 3   cluster_id            4536 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 141.9 KB
Done id 4FC32141-E888-4BFF-8804-12559A491D8C
Start id 5119D0F8-FCA8-4184-A4EB-19421A40DE0D
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5953 entries, 0 to 5952
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5953 non-null   float64
 1   next_start_timestamp  5953 non-null   float64
 2   end_timestamp         5953 non-null   float64
 3   cluster_id            5953 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 186.2 KB
Done id 5119D0F8-FCA8-4184-A4EB-19421A40DE0D
Start id 5152A2DF-FAF3-4BA8-9CA9-E66B32671A53
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6353 entries, 0 to 6352
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6353 non-null   float64
 1   next_start_timestamp  6353 non-null   float64
 2   end_timestamp         6353 non-null   float64
 3   cluster_id            6353 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 198.7 KB
Done id 5152A2DF-FAF3-4BA8-9CA9-E66B32671A53
Start id 59818CD2-24D7-4D32-B133-24C2FE3801E5
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2407 entries, 0 to 2406
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       2407 non-null   float64
 1   next_start_timestamp  2407 non-null   float64
 2   end_timestamp         2407 non-null   float64
 3   cluster_id            2407 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 75.3 KB
Done id 59818CD2-24D7-4D32-B133-24C2FE3801E5
Start id 59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6653 entries, 0 to 6652
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6653 non-null   float64
 1   next_start_timestamp  6653 non-null   float64
 2   end_timestamp         6653 non-null   float64
 3   cluster_id            6653 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 208.0 KB
Done id 59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2
Start id 5EF64122-B513-46AE-BCF1-E62AAC285D2C
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3304 entries, 0 to 3303
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       3304 non-null   float64
 1   next_start_timestamp  3304 non-null   float64
 2   end_timestamp         3304 non-null   float64
 3   cluster_id            3304 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 103.4 KB
Done id 5EF64122-B513-46AE-BCF1-E62AAC285D2C
Start id 61359772-D8D8-480D-B623-7C636EAD0C81
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5433 entries, 0 to 5432
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5433 non-null   float64
 1   next_start_timestamp  5433 non-null   float64
 2   end_timestamp         5433 non-null   float64
 3   cluster_id            5433 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 169.9 KB
Done id 61359772-D8D8-480D-B623-7C636EAD0C81
Start id 61976C24-1C50-4355-9C49-AAE44A7D09F6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5590 entries, 0 to 5589
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5590 non-null   float64
 1   next_start_timestamp  5590 non-null   float64
 2   end_timestamp         5590 non-null   float64
 3   cluster_id            5590 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 174.8 KB
Done id 61976C24-1C50-4355-9C49-AAE44A7D09F6
Start id 665514DE-49DC-421F-8DCB-145D0B2609AD
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6656 entries, 0 to 6655
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6656 non-null   float64
 1   next_start_timestamp  6656 non-null   float64
 2   end_timestamp         6656 non-null   float64
 3   cluster_id            6656 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 208.1 KB
Done id 665514DE-49DC-421F-8DCB-145D0B2609AD
Start id 74B86067-5D4B-43CF-82CF-341B76BEA0F4
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6563 entries, 0 to 6562
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       6563 non-null   float64
 1   next_start_timestamp  6563 non-null   float64
 2   end_timestamp         6563 non-null   float64
 3   cluster_id            6563 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 205.2 KB
Done id 74B86067-5D4B-43CF-82CF-341B76BEA0F4
Start id 78A91A4E-4A51-4065-BDA7-94755F0BB3BB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8209 entries, 0 to 8208
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       8209 non-null   float64
 1   next_start_timestamp  8209 non-null   float64
 2   end_timestamp         8209 non-null   float64
 3   cluster_id            8209 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 256.7 KB
Done id 78A91A4E-4A51-4065-BDA7-94755F0BB3BB
Start id 797D145F-3858-4A7F-A7C2-A4EB721E133C
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2597 entries, 0 to 2596
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       2597 non-null   float64
 1   next_start_timestamp  2597 non-null   float64
 2   end_timestamp         2597 non-null   float64
 3   cluster_id            2597 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 81.3 KB
Done id 797D145F-3858-4A7F-A7C2-A4EB721E133C
Start id 7CE37510-56D0-4120-A1CF-0E23351428D2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9679 entries, 0 to 9678
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       9679 non-null   float64
 1   next_start_timestamp  9679 non-null   float64
 2   end_timestamp         9679 non-null   float64
 3   cluster_id            9679 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 302.6 KB
Done id 7CE37510-56D0-4120-A1CF-0E23351428D2
Start id 7D9BB102-A612-4E2A-8E22-3159752F55D8
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       600 non-null    float64
 1   next_start_timestamp  600 non-null    float64
 2   end_timestamp         600 non-null    float64
 3   cluster_id            600 non-null    int64
dtypes: float64(3), int64(1)
memory usage: 18.9 KB
Done id 7D9BB102-A612-4E2A-8E22-3159752F55D8
Start id 8023FE1A-D3B0-4E2C-A57A-9321B7FC755F
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7743 entries, 0 to 7742
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       7743 non-null   float64
 1   next_start_timestamp  7743 non-null   float64
 2   end_timestamp         7743 non-null   float64
 3   cluster_id            7743 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 242.1 KB
Done id 8023FE1A-D3B0-4E2C-A57A-9321B7FC755F
Start id 806289BC-AD52-4CC1-806C-0CDB14D65EB6
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8166 entries, 0 to 8165
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       8166 non-null   float64
 1   next_start_timestamp  8166 non-null   float64
 2   end_timestamp         8166 non-null   float64
 3   cluster_id            8166 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 255.3 KB
Done id 806289BC-AD52-4CC1-806C-0CDB14D65EB6
Start id 81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5073 entries, 0 to 5072
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       5073 non-null   float64
 1   next_start_timestamp  5073 non-null   float64
 2   end_timestamp         5073 non-null   float64
 3   cluster_id            5073 non-null   int64
dtypes: float64(3), int64(1)
memory usage: 158.7 KB

KeyboardInterrupt:

In [81]:

len(wellness_user_inputs.keys())

34

    timestamp    context
0  1444079161  [Unknown]
1  1444079221  [Unknown]
2  1444079281  [Unknown]
3  1444079341  [Unknown]
4  1444079431  [Unknown]

Done id 00EABED2-271D-49D8-B599-1D4A09240601

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40442 entries, 0 to 40441
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   start_timestamp       40442 non-null  float64
 1   next_start_timestamp  40442 non-null  float64
 2   end_timestamp         40442 non-null  float64
 3   cluster_id            40442 non-null  int64
dtypes: float64(3), int64(1)
memory usage: 1.2 MB

             pred_context     context
timestamp
1.342781e+09         None  [Sleeping]
1.342781e+09         None  [Sleeping]
1.342781e+09         None  [Sleeping]
1.342781e+09         None  [Sleeping]
1.342781e+09         None  [Sleeping]

In [32]:

df_combined_ts.head()

         timestamp    context
196866  1308130861  HouseWork
196867  1308130864  HouseWork
196868  1308130883  HouseWork
196869  1308130890  HouseWork
196870  1308130914  HouseWork

In [33]:
df_wellness_input = df_combined_ts

In [72]:
user_wellness_scores = {}
for id in wellness_user_inputs.keys():
    df_wellness_input = wellness_user_inputs[id].copy(deep=True)
    df_wellness_input['datetime'] = pd.to_datetime(df_wellness_input['timestamp'], unit='s')
    df_wellness_input['week'] = df_wellness_input['datetime'].apply(lambda x: x.strftime("%Y_%V"))
    df_wellness_input['day'] = df_wellness_input['datetime'].apply(lambda x: x.strftime("%Y-%m-%d"))

    user_week_context_attributes = []
    for week in df_wellness_input['week'].unique():
        df_week_wellness_input = df_wellness_input[df_wellness_input.week == week]
        week_context_attributes = {}
        for day in df_week_wellness_input['day'].unique():
            df_day_wellness_input = df_week_wellness_input[df_week_wellness_input.day == day]
            df_day_wellness_input['context_grp'] = (
                    df_day_wellness_input['context'] != df_day_wellness_input['context'].shift(1)).cumsum()
            day_contexts = df_day_wellness_input.groupby(['context_grp', 'context'], as_index=False).agg({
                'timestamp': ['min', 'max', lambda x: x.max() - x.min()]
            })
            day_contexts.columns = ['group', 'context', 'start', 'end', 'length']
            week_context_attributes[day] = day_contexts
        user_week_context_attributes.append([week, week_context_attributes])
        print(f'Done week {week}.')
    weekly_stress_scores = []
    for week, week_context_attributes in user_week_context_attributes:
        week_stress_score = get_weekly_stress_score(week_context_attributes)
        weekly_stress_scores.append((week, week_stress_score))
    user_wellness_scores[id] = weekly_stress_scores
    print(f"Done user {id}")
    # break

Done week 2015_41.
Done week 2015_42.
Done user 00EABED2-271D-49D8-B599-1D4A09240601
Done week 2015_32.
Done week 2015_34.
Done week 2015_35.
Done week 2015_36.
Done user 098A72A5-E3E5-4F54-A152-BBDA0DF7B694
Done week 2015_50.
Done user 0A986513-7828-4D53-AA1F-E02D6DF9561B
Done week 2015_43.
Done week 2015_44.
Done user 0BFC35E2-4817-4865-BFA7-764742302A2D
Done week 2015_49.
Done week 2015_50.
Done user 0E6184E1-90C0-48EE-B25A-F1ECB7B9714E
Done week 2016_21.
Done week 2016_22.
Done user 1155FF54-63D3-4AB2-9863-8385D0BD0A13
Done week 2015_34.
Done week 2015_35.
Done user 11B5EC4D-4133-4289-B475-4E737182A406
Done week 2015_34.
Done week 2015_35.
Done user 136562B6-95B2-483D-88DC-065F28409FD2
Done week 2015_43.
Done week 2015_44.
Done user 1538C99F-BA1E-4EFB-A949-6C7C47701B20
Done week 2015_35.
Done week 2015_36.
Done user 1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842
Done week 2015_43.
Done week 2015_44.
Done week 2015_45.
Done user 24E40C4C-A349-4F9F-93AB-01D00FB994AF
Done week 2015_48.
Done week 2015_49.
Done user 27E04243-B138-4F40-A164-F40B60165CF3
Done week 2015_34.
Done week 2015_33.
Done user 2C32C23E-E30C-498A-8DD2-0EFB9150A02E
Done week 2015_36.
Done week 2015_37.
Done user 33A85C34-CFE4-4732-9E73-0A7AC861B27A
Done week 2015_45.
Done week 2015_46.
Done user 3600D531-0C55-44A7-AE95-A7A38519464E
Done week 2015_51.
Done week 2015_52.
Done user 40E170A7-607B-4578-AF04-F021C3B0384A
Done week 2016_21.
Done week 2016_22.
Done user 481F4DD2-7689-43B9-A2AA-C8772227162B
Done week 2015_46.
Done week 2015_45.
Done user 4E98F91F-4654-42EF-B908-A3389443F2E7
Done week 2015_34.
Done week 2015_35.
Done user 4FC32141-E888-4BFF-8804-12559A491D8C
Done week 2015_39.
Done week 2015_40.
Done user 5119D0F8-FCA8-4184-A4EB-19421A40DE0D
Done week 2015_39.
Done week 2015_40.
Done user 5152A2DF-FAF3-4BA8-9CA9-E66B32671A53
Done week 2016_21.
Done week 2016_22.
Done user 59818CD2-24D7-4D32-B133-24C2FE3801E5
Done week 2016_21.
Done week 2016_22.
Done user 59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2
Done week 2015_38.
Done user 5EF64122-B513-46AE-BCF1-E62AAC285D2C
Done week 2015_42.
Done week 2015_43.
Done user 61359772-D8D8-480D-B623-7C636EAD0C81
Done week 2015_23.
Done week 2015_24.
Done week 2015_40.
Done week 2015_41.
Done user 61976C24-1C50-4355-9C49-AAE44A7D09F6
Done week 2015_49.
Done week 2015_50.
Done user 665514DE-49DC-421F-8DCB-145D0B2609AD
Done week 2015_36.
Done week 2015_37.
Done user 74B86067-5D4B-43CF-82CF-341B76BEA0F4
Done week 2015_49.
Done week 2015_50.
Done user 78A91A4E-4A51-4065-BDA7-94755F0BB3BB
Done week 2015_50.
Done week 2015_51.
Done user 797D145F-3858-4A7F-A7C2-A4EB721E133C
Done week 2015_41.
Done week 2015_42.
Done user 7CE37510-56D0-4120-A1CF-0E23351428D2
Done week 2015_47.
Done week 2015_48.
Done user 7D9BB102-A612-4E2A-8E22-3159752F55D8
Done week 2015_44.
Done week 2015_45.
Done user 8023FE1A-D3B0-4E2C-A57A-9321B7FC755F
Done week 2015_48.
Done week 2015_49.
Done user 806289BC-AD52-4CC1-806C-0CDB14D65EB6
Done week 2015_44.
Done week 2015_45.
Done user 81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0
Done week 2015_50.
Done week 2015_51.
Done user 83CF687B-7CEC-434B-9FE8-00C3D5799BE6
Done week 2015_34.
Done week 2015_35.
Done week 2015_36.
Done user 86A4F379-B305-473D-9D83-FC7D800180EF
Done week 2015_48.
Done week 2015_49.
Done user 96A358A0-FFF2-4239-B93E-C7425B901B47
Done week 2015_37.
Done week 2015_38.
Done user 9759096F-1119-4E19-A0AD-6F16989C7E1C
Done week 2015_41.
Done week 2015_42.
Done user 99B204C0-DD5C-4BB7-83E8-A37281B8D769
Done week 2015_49.
Done week 2015_50.
Done user 9DC38D04-E82E-4F29-AB52-B476535226F2
Done week 2015_30.
Done week 2015_31.
Done user A5A30F76-581E-4757-97A2-957553A2C6AA
Done week 2015_35.
Done week 2015_36.
Done user A5CDF89D-02A2-4EC1-89F8-F534FDABDD96
Done week 2015_45.
Done week 2015_46.
Done user A7599A50-24AE-46A6-8EA6-2576F1011D81
Done week 2015_39.
Done week 2015_40.
Done user A76A5AF5-5A93-4CF2-A16E-62353BB70E8A
Done week 2015_45.
Done week 2015_46.
Done week 2015_47.
Done user B09E373F-8A54-44C8-895B-0039390B859F
Done week 2015_35.
Done week 2015_36.
Done user B7F9D634-263E-4A97-87F9-6FFB4DDCB36C
Done week 2015_47.
Done week 2015_48.
Done user B9724848-C7E2-45F4-9B3F-A1F38D864495
Done week 2015_42.
Done week 2015_43.
Done user BE3CA5A6-A561-4BBD-B7C9-5DF6805400FC
Done week 2015_31.
Done week 2015_32.
Done user BEF6C611-50DA-4971-A040-87FB979F3FC1
Done week 2015_40.
Done week 2015_41.
Done user C48CE857-A0DD-4DDB-BEA5-3A25449B2153
Done week 2015_35.
Done week 2015_36.
Done user CA820D43-E5E2-42EF-9798-BE56F776370B
Done week 2015_42.
Done week 2015_43.
Done user CCAF77F0-FABB-4F2F-9E24-D56AD0C5A82F
Done week 2015_37.
Done user CDA3BBF7-6631-45E8-85BA-EEB416B32A3C
Done week 2015_47.
Done user CF722AA9-2533-4E51-9FEB-9EAC84EE9AAC
Done week 2015_33.
Done week 2015_34.
Done user D7D20E2E-FC78-405D-B346-DBD3FD8FC92B
Done week 2015_38.
Done user E65577C1-8D5D-4F70-AF23-B3ADB9D3DBA3
Done week 2015_46.
Done week 2015_47.
Done user ECECC2AB-D32F-4F90-B74C-E12A1C69BBE2
Done week 2015_37.
Done week 2015_38.
Done user F50235E0-DD67-4F2A-B00B-1F31ADA998B9
Done week 2015_40.
Done week 2015_41.
Done user FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF

In [73]:
user_wellness_scores

{'00EABED2-271D-49D8-B599-1D4A09240601': [('2015_41', 2.0), ('2015_42', 2.5)],
 '098A72A5-E3E5-4F54-A152-BBDA0DF7B694': [('2015_32', 3.0),
  ('2015_34', 0.0),
  ('2015_35', 1.5),
  ('2015_36', 2.5)],
 '0A986513-7828-4D53-AA1F-E02D6DF9561B': [('2015_50', 0.5)],
 '0BFC35E2-4817-4865-BFA7-764742302A2D': [('2015_43', 1.5), ('2015_44', 1.0)],
 '0E6184E1-90C0-48EE-B25A-F1ECB7B9714E': [('2015_49', 4.0), ('2015_50', 2.0)],
 '1155FF54-63D3-4AB2-9863-8385D0BD0A13': [('2016_21', 5.0), ('2016_22', 2.0)],
 '11B5EC4D-4133-4289-B475-4E737182A406': [('2015_34', 1.5), ('2015_35', -0.5)],
 '136562B6-95B2-483D-88DC-065F28409FD2': [('2015_34', 4.5), ('2015_35', 0.0)],
 '1538C99F-BA1E-4EFB-A949-6C7C47701B20': [('2015_43', 1.0), ('2015_44', 2.5)],
 '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842': [('2015_35', 2.5), ('2015_36', 3.5)],
 '24E40C4C-A349-4F9F-93AB-01D00FB994AF': [('2015_43', 3.5),
  ('2015_44', 2.0),
  ('2015_45', 2.0)],
 '27E04243-B138-4F40-A164-F40B60165CF3': [('2015_48', 5.0), ('2015_49', 2.0)],
 '2C32C23E-E30C-498A-8DD2-0EFB9150A02E': [('2015_34', 1.5), ('2015_33', 0.5)],
 '33A85C34-CFE4-4732-9E73-0A7AC861B27A': [('2015_36', 2.0), ('2015_37', 2.0)],
 '3600D531-0C55-44A7-AE95-A7A38519464E': [('2015_45', 2.0), ('2015_46', 1.0)],
 '40E170A7-607B-4578-AF04-F021C3B0384A': [('2015_51', 2.5), ('2015_52', 1.0)],
 '481F4DD2-7689-43B9-A2AA-C8772227162B': [('2016_21', 2.5), ('2016_22', 4.0)],
 '4E98F91F-4654-42EF-B908-A3389443F2E7': [('2015_46', 2.0), ('2015_45', 3.0)],
 '4FC32141-E888-4BFF-8804-12559A491D8C': [('2015_34', -1.0), ('2015_35', 0.5)],
 '5119D0F8-FCA8-4184-A4EB-19421A40DE0D': [('2015_39', 3.5), ('2015_40', 0.0)],
 '5152A2DF-FAF3-4BA8-9CA9-E66B32671A53': [('2015_39', 1.5), ('2015_40', 2.5)],
 '59818CD2-24D7-4D32-B133-24C2FE3801E5': [('2016_21', 0.5), ('2016_22', 1.5)],
 '59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2': [('2016_21', 2.5), ('2016_22', 3.5)],
 '5EF64122-B513-46AE-BCF1-E62AAC285D2C': [('2015_38', 3.5)],
 '61359772-D8D8-480D-B623-7C636EAD0C81': [('2015_42', 0.0), ('2015_43', 1.5)],
 '61976C24-1C50-4355-9C49-AAE44A7D09F6': [('2015_23', 4.5),
  ('2015_24', 4.0),
  ('2015_40', 1.0),
  ('2015_41', -0.5)],
 '665514DE-49DC-421F-8DCB-145D0B2609AD': [('2015_49', 2.0), ('2015_50', 4.0)],
 '74B86067-5D4B-43CF-82CF-341B76BEA0F4': [('2015_36', 0.0), ('2015_37', 2.0)],
 '78A91A4E-4A51-4065-BDA7-94755F0BB3BB': [('2015_49', 3.5), ('2015_50', 1.5)],
 '797D145F-3858-4A7F-A7C2-A4EB721E133C': [('2015_50', 0.5), ('2015_51', -0.5)],
 '7CE37510-56D0-4120-A1CF-0E23351428D2': [('2015_41', 3.0), ('2015_42', 2.5)],
 '7D9BB102-A612-4E2A-8E22-3159752F55D8': [('2015_47', 4.0), ('2015_48', 2.0)],
 '8023FE1A-D3B0-4E2C-A57A-9321B7FC755F': [('2015_44', 2.0), ('2015_45', -1.0)],
 '806289BC-AD52-4CC1-806C-0CDB14D65EB6': [('2015_48', 3.0), ('2015_49', 2.5)],
 '81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0': [('2015_44', 2.5), ('2015_45', 1.5)],
 '83CF687B-7CEC-434B-9FE8-00C3D5799BE6': [('2015_50', 2.5), ('2015_51', -0.5)],
 '86A4F379-B305-473D-9D83-FC7D800180EF': [('2015_34', 1.5),
  ('2015_35', 2.0),
  ('2015_36', 1.5)],
 '96A358A0-FFF2-4239-B93E-C7425B901B47': [('2015_48', 1.0), ('2015_49', 2.5)],
 '9759096F-1119-4E19-A0AD-6F16989C7E1C': [('2015_37', 2.0), ('2015_38', -2.0)],
 '99B204C0-DD5C-4BB7-83E8-A37281B8D769': [('2015_41', 3.0), ('2015_42', 0.5)],
 '9DC38D04-E82E-4F29-AB52-B476535226F2': [('2015_49', 3.0), ('2015_50', -1.5)],
 'A5A30F76-581E-4757-97A2-957553A2C6AA': [('2015_30', 2.5), ('2015_31', 1.0)],
 'A5CDF89D-02A2-4EC1-89F8-F534FDABDD96': [('2015_35', 4.0), ('2015_36', 1.5)],
 'A7599A50-24AE-46A6-8EA6-2576F1011D81': [('2015_45', 4.0), ('2015_46', 4.5)],
 'A76A5AF5-5A93-4CF2-A16E-62353BB70E8A': [('2015_39', 0.0), ('2015_40', -1.0)],
 'B09E373F-8A54-44C8-895B-0039390B859F': [('2015_45', 0.5),
  ('2015_46', 2.0),
  ('2015_47', 1.5)],
 'B7F9D634-263E-4A97-87F9-6FFB4DDCB36C': [('2015_35', 4.0), ('2015_36', -0.5)],
 'B9724848-C7E2-45F4-9B3F-A1F38D864495': [('2015_47', 3.0), ('2015_48', 1.0)],
 'BE3CA5A6-A561-4BBD-B7C9-5DF6805400FC': [('2015_42', -1.5),
  ('2015_43', -2.0)],
 'BEF6C611-50DA-4971-A040-87FB979F3FC1': [('2015_31', 1.5), ('2015_32', 3.0)],
 'C48CE857-A0DD-4DDB-BEA5-3A25449B2153': [('2015_40', 4.0), ('2015_41', 3.0)],
 'CA820D43-E5E2-42EF-9798-BE56F776370B': [('2015_35', 1.5), ('2015_36', 1.0)],
 'CCAF77F0-FABB-4F2F-9E24-D56AD0C5A82F': [('2015_42', 4.0), ('2015_43', 2.5)],
 'CDA3BBF7-6631-45E8-85BA-EEB416B32A3C': [('2015_37', 0.5)],
 'CF722AA9-2533-4E51-9FEB-9EAC84EE9AAC': [('2015_47', 4.0)],
 'D7D20E2E-FC78-405D-B346-DBD3FD8FC92B': [('2015_33', 2.5), ('2015_34', 1.0)],
 'E65577C1-8D5D-4F70-AF23-B3ADB9D3DBA3': [('2015_38', 2.5)],
 'ECECC2AB-D32F-4F90-B74C-E12A1C69BBE2': [('2015_46', 2.0), ('2015_47', 2.5)],
 'F50235E0-DD67-4F2A-B00B-1F31ADA998B9': [('2015_37', 1.0), ('2015_38', 0.0)],
 'FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF': [('2015_40', 5.0), ('2015_41', 1.0)]}

In [38]:
wellness_user_inputs.keys()

dict_keys(['00EABED2-271D-49D8-B599-1D4A09240601', '098A72A5-E3E5-4F54-A152-BBDA0DF7B694', '0A986513-7828-4D53-AA1F-E02D6DF9561B', '0BFC35E2-4817-4865-BFA7-764742302A2D', '0E6184E1-90C0-48EE-B25A-F1ECB7B9714E', '1155FF54-63D3-4AB2-9863-8385D0BD0A13', '11B5EC4D-4133-4289-B475-4E737182A406', '136562B6-95B2-483D-88DC-065F28409FD2', '1538C99F-BA1E-4EFB-A949-6C7C47701B20', '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842', '24E40C4C-A349-4F9F-93AB-01D00FB994AF', '27E04243-B138-4F40-A164-F40B60165CF3', '2C32C23E-E30C-498A-8DD2-0EFB9150A02E', '33A85C34-CFE4-4732-9E73-0A7AC861B27A', '3600D531-0C55-44A7-AE95-A7A38519464E', '40E170A7-607B-4578-AF04-F021C3B0384A', '481F4DD2-7689-43B9-A2AA-C8772227162B', '4E98F91F-4654-42EF-B908-A3389443F2E7', '4FC32141-E888-4BFF-8804-12559A491D8C', '5119D0F8-FCA8-4184-A4EB-19421A40DE0D', '5152A2DF-FAF3-4BA8-9CA9-E66B32671A53', '59818CD2-24D7-4D32-B133-24C2FE3801E5', '59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2', '5EF64122-B513-46AE-BCF1-E62AAC285D2C', '61359772-D8D8-480D-B623-7C636EAD0C81', '61976C24-1C50-4355-9C49-AAE44A7D09F6', '665514DE-49DC-421F-8DCB-145D0B2609AD', '74B86067-5D4B-43CF-82CF-341B76BEA0F4', '78A91A4E-4A51-4065-BDA7-94755F0BB3BB', '797D145F-3858-4A7F-A7C2-A4EB721E133C', '7CE37510-56D0-4120-A1CF-0E23351428D2', '7D9BB102-A612-4E2A-8E22-3159752F55D8', '8023FE1A-D3B0-4E2C-A57A-9321B7FC755F', '806289BC-AD52-4CC1-806C-0CDB14D65EB6', '81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0', '83CF687B-7CEC-434B-9FE8-00C3D5799BE6', '86A4F379-B305-473D-9D83-FC7D800180EF', '96A358A0-FFF2-4239-B93E-C7425B901B47', '9759096F-1119-4E19-A0AD-6F16989C7E1C', '99B204C0-DD5C-4BB7-83E8-A37281B8D769', '9DC38D04-E82E-4F29-AB52-B476535226F2', 'A5A30F76-581E-4757-97A2-957553A2C6AA', 'A5CDF89D-02A2-4EC1-89F8-F534FDABDD96', 'A7599A50-24AE-46A6-8EA6-2576F1011D81', 'A76A5AF5-5A93-4CF2-A16E-62353BB70E8A', 'B09E373F-8A54-44C8-895B-0039390B859F', 'B7F9D634-263E-4A97-87F9-6FFB4DDCB36C', 'B9724848-C7E2-45F4-9B3F-A1F38D864495', 'BE3CA5A6-A561-4BBD-B7C9-5DF6805400FC', 'BEF6C611-50DA-4971-A040-87FB979F3FC1', 'C48CE857-A0DD-4DDB-BEA5-3A25449B2153', 'CA820D43-E5E2-42EF-9798-BE56F776370B', 'CCAF77F0-FABB-4F2F-9E24-D56AD0C5A82F', 'CDA3BBF7-6631-45E8-85BA-EEB416B32A3C', 'CF722AA9-2533-4E51-9FEB-9EAC84EE9AAC', 'D7D20E2E-FC78-405D-B346-DBD3FD8FC92B', 'E65577C1-8D5D-4F70-AF23-B3ADB9D3DBA3', 'ECECC2AB-D32F-4F90-B74C-E12A1C69BBE2', 'F50235E0-DD67-4F2A-B00B-1F31ADA998B9', 'FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF'])

In [36]:
weekly_stress_scores = []
for week, week_context_attributes in user_week_context_attributes:
    week_stress_score = get_weekly_stress_score(user_week_context_attributes[0][1])
    weekly_stress_scores.append((week, week_stress_score))
weekly_stress_scores

[('2011_24', 1.0),
 ('2011_25', 1.0),
 ('2011_26', 1.0),
 ('2011_27', 1.0),
 ('2011_28', 1.0),
 ('2011_29', 1.0),
 ('2011_30', 1.0),
 ('2011_31', 1.0),
 ('2011_32', 1.0),
 ('2011_33', 1.0)]

In [12]:
user_week_context_attributes[0]

['2012_29',
 {'2012-07-20':     group        context       start         end  length
  0       1       GoingOut  1342780734  1342781454     720
  1       3  UsingBathroom  1342782560  1342782599      39
  2       5  UsingBathroom  1342782609  1342782609       0
  3       6      PhoneCall  1342785004  1342785340     336
  4       9  UsingBathroom  1342785645  1342785930     285
  5      12       GoingOut  1342786003  1342786018      15
  6      13       ComingIn  1342786433  1342786450      17
  7      14       Sleeping  1342786485  1342787744    1259
  8      16       Sleeping  1342787819  1342789329    1510
  9      17        Unknown  1342789491  1342789491       0
  10     18       GoingOut  1342789494  1342789509      15
  11     19       ComingIn  1342795232  1342795247      15
  12     22  UsingBathroom  1342795272  1342795407     135
  13     25       Sleeping  1342795479  1342796390     911
  14     26        Unknown  1342796446  1342796450       4
  15     27     HavingMeal  1342796456  1342796564     108
  16     28        Unknown  1342796567  1342796567       0
  17     31       Sleeping  1342796579  1342804452    7873
  18     33  UsingBathroom  1342804632  1342805202     570
  19     37  UsingBathroom  1342806018  1342806055      37
  20     40       Relaxing  1342806075  1342807254    1179
  21     42       GoingOut  1342807315  1342807333      18
  22     44       ComingIn  1342812168  1342812182      14
  23     46       ComingIn  1342812184  1342812186       2
  24     48       ComingIn  1342812188  1342812188       0
  25     50       Relaxing  1342812196  1342817982    5786
  26     52       Relaxing  1342818052  1342818052       0
  27     53  UsingBathroom  1342818324  1342818452     128
  28     55  UsingBathroom  1342818473  1342818607     134
  29     56        Unknown  1342818945  1342818945       0
  30     57     HavingMeal  1342818946  1342819044      98
  31     58       Sleeping  1342819057  1342827881    8824,
  '2012-07-21':     group        context       start         end  length
  0       1       Sleeping  1342829081  1342831480    2399
  1       3  UsingBathroom  1342831513  1342831717     204
  2       4       Sleeping  1342850912  1342850919       7
  3       5  UsingBathroom  1342850931  1342851090     159
  4       7     OfficeWork  1342851352  1342853647    2295
  ..    ...            ...         ...         ...     ...
  66    102     HavingMeal  1342914068  1342914187     119
  67    103  UsingBathroom  1342914335  1342914603     268
  68    105  UsingBathroom  1342914610  1342915085     475
  69    106        Unknown  1342915095  1342915095       0
  70    107       Sleeping  1342915096  1342915198     102

  [71 rows x 5 columns],
  '2012-07-22':     group        context       start         end  length
  0       1       Sleeping  1342915200  1342926968   11768
  1       3        Unknown  1342926983  1342926983       0
  2       4  UsingBathroom  1342926984  1342926984       0
  3       5        Unknown  1342926986  1342926986       0
  4       6  UsingBathroom  1342926991  1342927235     244
  ..    ...            ...         ...         ...     ...
  63     88        Unknown  1343000796  1343000804       8
  64     89     HavingMeal  1343000816  1343000998     182
  65     90        Unknown  1343000999  1343001054      55
  66     91  UsingBathroom  1343001055  1343001575     520
  67     94  UsingBathroom  1343001589  1343001598       9

  [68 rows x 5 columns]}]

In [40]:
user_wellness_scores

{'00EABED2-271D-49D8-B599-1D4A09240601': [('2015_41', 2.0), ('2015_42', 2.0)],
 '098A72A5-E3E5-4F54-A152-BBDA0DF7B694': [('2015_32', 3.0),
  ('2015_34', 3.0),
  ('2015_35', 3.0),
  ('2015_36', 3.0)],
 '0A986513-7828-4D53-AA1F-E02D6DF9561B': [('2015_50', 0.5)],
 '0BFC35E2-4817-4865-BFA7-764742302A2D': [('2015_43', 1.5), ('2015_44', 1.5)],
 '0E6184E1-90C0-48EE-B25A-F1ECB7B9714E': [('2015_49', 4.0), ('2015_50', 4.0)],
 '1155FF54-63D3-4AB2-9863-8385D0BD0A13': [('2016_21', 5.0), ('2016_22', 5.0)],
 '11B5EC4D-4133-4289-B475-4E737182A406': [('2015_34', 1.5), ('2015_35', 1.5)],
 '136562B6-95B2-483D-88DC-065F28409FD2': [('2015_34', 4.5), ('2015_35', 4.5)],
 '1538C99F-BA1E-4EFB-A949-6C7C47701B20': [('2015_43', 1.0), ('2015_44', 1.0)],
 '1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842': [('2015_35', 2.5), ('2015_36', 2.5)],
 '24E40C4C-A349-4F9F-93AB-01D00FB994AF': [('2015_43', 3.5),
  ('2015_44', 3.5),
  ('2015_45', 3.5)],
 '27E04243-B138-4F40-A164-F40B60165CF3': [('2015_48', 5.0), ('2015_49', 5.0)],
 '2C32C23E-E30C-498A-8DD2-0EFB9150A02E': [('2015_34', 1.5), ('2015_33', 1.5)],
 '33A85C34-CFE4-4732-9E73-0A7AC861B27A': [('2015_36', 2.0), ('2015_37', 2.0)],
 '3600D531-0C55-44A7-AE95-A7A38519464E': [('2015_45', 2.0), ('2015_46', 2.0)],
 '40E170A7-607B-4578-AF04-F021C3B0384A': [('2015_51', 2.5), ('2015_52', 2.5)],
 '481F4DD2-7689-43B9-A2AA-C8772227162B': [('2016_21', 2.5), ('2016_22', 2.5)],
 '4E98F91F-4654-42EF-B908-A3389443F2E7': [('2015_46', 2.0), ('2015_45', 2.0)],
 '4FC32141-E888-4BFF-8804-12559A491D8C': [('2015_34', -1.0),
  ('2015_35', -1.0)],
 '5119D0F8-FCA8-4184-A4EB-19421A40DE0D': [('2015_39', 3.5), ('2015_40', 3.5)],
 '5152A2DF-FAF3-4BA8-9CA9-E66B32671A53': [('2015_39', 1.5), ('2015_40', 1.5)],
 '59818CD2-24D7-4D32-B133-24C2FE3801E5': [('2016_21', 0.5), ('2016_22', 0.5)],
 '59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2': [('2016_21', 2.5), ('2016_22', 2.5)],
 '5EF64122-B513-46AE-BCF1-E62AAC285D2C': [('2015_38', 3.5)],
 '61359772-D8D8-480D-B623-7C636EAD0C81': [('2015_42', 0.0), ('2015_43', 0.0)],
 '61976C24-1C50-4355-9C49-AAE44A7D09F6': [('2015_23', 4.5),
  ('2015_24', 4.5),
  ('2015_40', 4.5),
  ('2015_41', 4.5)],
 '665514DE-49DC-421F-8DCB-145D0B2609AD': [('2015_49', 2.0), ('2015_50', 2.0)],
 '74B86067-5D4B-43CF-82CF-341B76BEA0F4': [('2015_36', 0.0), ('2015_37', 0.0)],
 '78A91A4E-4A51-4065-BDA7-94755F0BB3BB': [('2015_49', 3.5), ('2015_50', 3.5)],
 '797D145F-3858-4A7F-A7C2-A4EB721E133C': [('2015_50', 0.5), ('2015_51', 0.5)],
 '7CE37510-56D0-4120-A1CF-0E23351428D2': [('2015_41', 3.0), ('2015_42', 3.0)],
 '7D9BB102-A612-4E2A-8E22-3159752F55D8': [('2015_47', 4.0), ('2015_48', 4.0)],
 '8023FE1A-D3B0-4E2C-A57A-9321B7FC755F': [('2015_44', 2.0), ('2015_45', 2.0)],
 '806289BC-AD52-4CC1-806C-0CDB14D65EB6': [('2015_48', 3.0), ('2015_49', 3.0)],
 '81536B0A-8DBF-4D8A-AC24-9543E2E4C8E0': [('2015_44', 2.5), ('2015_45', 2.5)],
 '83CF687B-7CEC-434B-9FE8-00C3D5799BE6': [('2015_50', 2.5), ('2015_51', 2.5)],
 '86A4F379-B305-473D-9D83-FC7D800180EF': [('2015_34', 1.5),
  ('2015_35', 1.5),
  ('2015_36', 1.5)],
 '96A358A0-FFF2-4239-B93E-C7425B901B47': [('2015_48', 1.0), ('2015_49', 1.0)],
 '9759096F-1119-4E19-A0AD-6F16989C7E1C': [('2015_37', 2.0), ('2015_38', 2.0)],
 '99B204C0-DD5C-4BB7-83E8-A37281B8D769': [('2015_41', 3.0), ('2015_42', 3.0)],
 '9DC38D04-E82E-4F29-AB52-B476535226F2': [('2015_49', 3.0), ('2015_50', 3.0)],
 'A5A30F76-581E-4757-97A2-957553A2C6AA': [('2015_30', 2.5), ('2015_31', 2.5)],
 'A5CDF89D-02A2-4EC1-89F8-F534FDABDD96': [('2015_35', 4.0), ('2015_36', 4.0)],
 'A7599A50-24AE-46A6-8EA6-2576F1011D81': [('2015_45', 4.0), ('2015_46', 4.0)],
 'A76A5AF5-5A93-4CF2-A16E-62353BB70E8A': [('2015_39', 0.0), ('2015_40', 0.0)],
 'B09E373F-8A54-44C8-895B-0039390B859F': [('2015_45', 0.5),
  ('2015_46', 0.5),
  ('2015_47', 0.5)],
 'B7F9D634-263E-4A97-87F9-6FFB4DDCB36C': [('2015_35', 4.0), ('2015_36', 4.0)],
 'B9724848-C7E2-45F4-9B3F-A1F38D864495': [('2015_47', 3.0), ('2015_48', 3.0)],
 'BE3CA5A6-A561-4BBD-B7C9-5DF6805400FC': [('2015_42', -1.5),
  ('2015_43', -1.5)],
 'BEF6C611-50DA-4971-A040-87FB979F3FC1': [('2015_31', 1.5), ('2015_32', 1.5)],
 'C48CE857-A0DD-4DDB-BEA5-3A25449B2153': [('2015_40', 4.0), ('2015_41', 4.0)],
 'CA820D43-E5E2-42EF-9798-BE56F776370B': [('2015_35', 1.5), ('2015_36', 1.5)],
 'CCAF77F0-FABB-4F2F-9E24-D56AD0C5A82F': [('2015_42', 4.0), ('2015_43', 4.0)],
 'CDA3BBF7-6631-45E8-85BA-EEB416B32A3C': [('2015_37', 0.5)],
 'CF722AA9-2533-4E51-9FEB-9EAC84EE9AAC': [('2015_47', 4.0)],
 'D7D20E2E-FC78-405D-B346-DBD3FD8FC92B': [('2015_33', 2.5), ('2015_34', 2.5)],
 'E65577C1-8D5D-4F70-AF23-B3ADB9D3DBA3': [('2015_38', 2.5)],
 'ECECC2AB-D32F-4F90-B74C-E12A1C69BBE2': [('2015_46', 2.0), ('2015_47', 2.0)],
 'F50235E0-DD67-4F2A-B00B-1F31ADA998B9': [('2015_37', 1.0), ('2015_38', 1.0)],
 'FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF': [('2015_40', 5.0), ('2015_41', 5.0)]}

In [82]:
productivity_user_inputs = None
for id in wellness_user_inputs.keys():
    prod_id_input = wellness_user_inputs[id].copy(deep=True)
    prod_id_input['datetime'] = pd.to_datetime(prod_id_input['timestamp'], unit='s')
    prod_id_input['week'] = prod_id_input['datetime'].apply(lambda x: x.strftime("%Y_%V"))
    prod_id_input['day'] = prod_id_input['datetime'].apply(lambda x: x.strftime("%Y-%m-%d"))
    prod_id_input['hourOfDay'] = prod_id_input['datetime'].apply(lambda x: x.strftime("%H"))
    prod_id_input = prod_id_input[['day','hourOfDay','context']]
    prod_id_input = prod_id_input.groupby(['day','hourOfDay'],as_index=False).agg({'context':[lambda x: (x=='OfficeWork').sum()/len(x), lambda x: ((x=='Amusement') | (x=='HavingMeal') | (x=='UsingBathroom')).sum()/len(x)]})
    prod_id_input.columns = ['day','hourOfDay','OfficeWork','Relaxing']
    prod_id_input['id'] = id
    prod_id_input = prod_id_input[['id','day','hourOfDay','OfficeWork','Relaxing']]
    if productivity_user_inputs is None:
        productivity_user_inputs = prod_id_input.copy(deep=True)
    else:
        productivity_user_inputs = pd.concat([productivity_user_inputs, prod_id_input], ignore_index=True)
    print(f"Done id {id}")

Done id 00EABED2-271D-49D8-B599-1D4A09240601
Done id 098A72A5-E3E5-4F54-A152-BBDA0DF7B694
Done id 0A986513-7828-4D53-AA1F-E02D6DF9561B
Done id 0BFC35E2-4817-4865-BFA7-764742302A2D
Done id 0E6184E1-90C0-48EE-B25A-F1ECB7B9714E
Done id 1155FF54-63D3-4AB2-9863-8385D0BD0A13
Done id 11B5EC4D-4133-4289-B475-4E737182A406
Done id 136562B6-95B2-483D-88DC-065F28409FD2
Done id 1538C99F-BA1E-4EFB-A949-6C7C47701B20
Done id 1DBB0F6F-1F81-4A50-9DF4-CD62ACFA4842
Done id 24E40C4C-A349-4F9F-93AB-01D00FB994AF
Done id 27E04243-B138-4F40-A164-F40B60165CF3
Done id 2C32C23E-E30C-498A-8DD2-0EFB9150A02E
Done id 33A85C34-CFE4-4732-9E73-0A7AC861B27A
Done id 3600D531-0C55-44A7-AE95-A7A38519464E
Done id 40E170A7-607B-4578-AF04-F021C3B0384A
Done id 481F4DD2-7689-43B9-A2AA-C8772227162B
Done id 4E98F91F-4654-42EF-B908-A3389443F2E7
Done id 4FC32141-E888-4BFF-8804-12559A491D8C
Done id 5119D0F8-FCA8-4184-A4EB-19421A40DE0D
Done id 5152A2DF-FAF3-4BA8-9CA9-E66B32671A53
Done id 59818CD2-24D7-4D32-B133-24C2FE3801E5
Done id 59EEFAE0-DEB0-4FFF-9250-54D2A03D0CF2
Done id 5EF64122-B513-46AE-BCF1-E62AAC285D2C
Done id 61359772-D8D8-480D-B623-7C636EAD0C81
Done id 61976C24-1C50-4355-9C49-AAE44A7D09F6
Done id 665514DE-49DC-421F-8DCB-145D0B2609AD
Done id 74B86067-5D4B-43CF-82CF-341B76BEA0F4
Done id 78A91A4E-4A51-4065-BDA7-94755F0BB3BB
Done id 797D145F-3858-4A7F-A7C2-A4EB721E133C
Done id 7CE37510-56D0-4120-A1CF-0E23351428D2
Done id 7D9BB102-A612-4E2A-8E22-3159752F55D8
Done id 8023FE1A-D3B0-4E2C-A57A-9321B7FC755F
Done id 806289BC-AD52-4CC1-806C-0CDB14D65EB6

In [83]:
productivity_user_inputs.info()
productivity_user_inputs.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3757 entries, 0 to 3756
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          3757 non-null   object
 1   day         3757 non-null   object
 2   hourOfDay   3757 non-null   object
 3   OfficeWork  3757 non-null   float64
 4   Relaxing    3757 non-null   float64
dtypes: float64(2), object(3)
memory usage: 146.9+ KB

,id,day,hourOfDay,OfficeWork,Relaxing
0,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,21,0.483871,0.080645
1,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,22,0.952381,0.000000
2,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-05,23,0.000000,0.227723
3,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-06,00,0.000000,0.444444
4,00EABED2-271D-49D8-B599-1D4A09240601,2015-10-06,01,0.000000,0.484305

In [84]:
productivity_user_inputs.to_csv("../../cache/productivity_input.csv",index=False)

In [78]:
productivity_user_inputs.Relaxing.sum()

0.0

,id,day,hourOfDay,OfficeWork,Relaxing
0,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-09-30,16,0.422222,0.0
1,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-09-30,17,0.009259,0.0
2,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-09-30,18,0.135135,0.0
3,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-09-30,19,0.300000,0.0
4,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-09-30,20,0.310811,0.0
...,...,...,...,...,...
56,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-10-07,03,0.000000,0.0
57,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-10-07,05,0.000000,0.0
58,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-10-07,06,0.000000,0.0
59,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-10-07,15,0.000000,0.0
60,FDAA70A1-42A3-4E3F-9AE3-3FDA412E03BF,2015-10-07,16,0.000000,0.0